# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: JÉSSICA SOARES
# Description of the Site
description: Psicoterapia online para brasileiros no exterior </br> Psicoterapia presencial em Natal/RN
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: terapia, Psicoterapia, psicologia, brasileiro, brasileiros, expatriados, exterior, online, virtual, on-line, psicóloga, psicólogo, Natal, Rio Grande do Norte, presencial, clínica, psicologia social, trabalho, depressão, burnout, sessão
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?cs=srgb&dl=pexels-andrea-piacquadio-3769021.jpg&fm=jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jessicarodfreitas@gmail.com
facebook_username: 
twitter_username: 
instagram_username: psi.jessicasoares
linkedin_username: 
github_username:  
youtube_channel_id:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Eliezio Soares
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/1655730?s=460&u=c3c4aeeca17a943b22950402d0d29b1b5985b967&v=4
# 60 Words About the Author
author-about: 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/elieziosoares

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
